# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: Microposts_development
  pool: 5
  username: postgres
  password: 123456

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: Microposts_test
  pool: 5
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  database: Microposts_production
  pool: 5
  username: postgres
  password: 123456

cucumber:
  <<: *TEST
